# Generated by Django 3.0.5 on 2020-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script_info',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_title', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('War', 'War'), ('Thriller', 'Thriller')], default='Mixed', max_length=20)),
                ('language_of_action_line', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='Mixed', max_length=20)),
                ('language_of_dialogues', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='Mixed', max_length=20)),
                ('type_of_script', models.CharField(choices=[('Roman', 'Roman'), ('Devnagri', 'Devnagri')], default='Mixed', max_length=20)),
                ('time', models.CharField(choices=[('Modern', 'Modern'), ('Contemporary', 'Contemporary'), ('Ancient', 'Ancient')], default='Mixed', max_length=20)),
                ('location', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='Mixed', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
