# Generated by Django 3.0.5 on 2020-11-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0003_auto_20201126_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script_info',
            old_name='author_name',
            new_name='Author_name',
        ),
    ]
