# Generated by Django 3.0.5 on 2020-11-26 08:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0004_auto_20201126_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script_info',
            name='city',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('Mumbai', 'Mumbai')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='country',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('War', 'War'), ('Thriller', 'Thriller')], default='', max_length=62),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='language_of_action_line',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='language_of_dialogues',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='script_written_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Roman', 'Roman'), ('Devnagri', 'Devnagri')], default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='time',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Modern', 'Modern'), ('Contemporary', 'Contemporary'), ('Ancient', 'Ancient')], default='', max_length=27),
        ),
    ]
