# Generated by Django 3.0.5 on 2020-11-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0005_auto_20201126_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script_info',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('Mumbai', 'Mumbai')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='country',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='language_of_action_line',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='language_of_dialogues',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='script_written_in',
            field=models.CharField(choices=[('Roman', 'Roman'), ('Devnagri', 'Devnagri')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='time',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Contemporary', 'Contemporary'), ('Ancient', 'Ancient')], default='', max_length=50),
        ),
    ]
