# Generated by Django 3.0.5 on 2020-11-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0006_auto_20201127_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script_info',
            name='language_of_action_line',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('German', 'German')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='script_info',
            name='language_of_dialogues',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('German', 'German')], default='', max_length=50),
        ),
    ]
