# Generated by Django 3.0.5 on 2020-11-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0008_auto_20201127_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='script_info',
            name='myfile',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
