# Generated by Django 3.0.5 on 2020-11-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0009_script_info_myfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script_info',
            old_name='myfile',
            new_name='upload',
        ),
    ]
