# Generated by Django 3.0.5 on 2020-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0010_auto_20201128_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script_info',
            name='upload',
            field=models.FileField(default='', upload_to='upload'),
        ),
    ]
