# Generated by Django 3.0.5 on 2020-11-30 08:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0012_auto_20201129_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_edit',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_avatar', models.ImageField(default='', upload_to='profile_avatar')),
                ('character_name', models.CharField(default='', max_length=50)),
                ('gender', multiselectfield.db.fields.MultiSelectField(choices=[('Men', 'Men'), ('Women', 'Women')], default='', max_length=9)),
                ('age_group', models.CharField(choices=[('Child', 'Child'), ('Infant', 'Infant'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior Age', 'Senior Age')], default='', max_length=50)),
                ('select_voice', models.CharField(choices=[('Child', 'Child'), ('Men', 'Men'), ('Women', 'Women'), ('Default', 'Default'), ('Senior Age', 'Senior Age')], default='', max_length=50)),
            ],
        ),
    ]
