# Generated by Django 3.0.5 on 2020-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0013_character_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_edit',
            name='profile_avatar',
        ),
        migrations.AddField(
            model_name='character_edit',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile_pic'),
        ),
    ]
