# Generated by Django 3.0.5 on 2020-11-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0014_auto_20201130_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_edit',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='character_edit',
            name='photograph',
            field=models.ImageField(default='', upload_to='photograph'),
        ),
    ]
