# Generated by Django 3.0.5 on 2020-11-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0015_auto_20201130_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_edit',
            name='photograph',
        ),
    ]
