# Generated by Django 3.0.5 on 2020-11-30 09:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0016_remove_character_edit_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_edit',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='character_edit',
            name='select_voice',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Child', 'Child'), ('Senior Age', 'Senior Age'), ('Default', 'Default')], default='', max_length=50),
        ),
    ]
