# Generated by Django 3.0.5 on 2020-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0018_character_edit_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_edit',
            name='select_voice',
        ),
        migrations.AddField(
            model_name='character_edit',
            name='selection',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='', max_length=50),
        ),
    ]
