# Generated by Django 3.0.5 on 2020-12-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0020_auto_20201202_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_edit',
            name='music',
            field=models.CharField(choices=[('Men', "{% static 'palak/sweeping_straw_broom-mike-koenig.mp3' %}"), ('Women', 'Women')], default='', max_length=50),
        ),
    ]
