# Generated by Django 3.0.5 on 2020-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0021_auto_20201202_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_edit',
            name='music',
            field=models.CharField(choices=[('Men', "{% static 'palak/sweeping_straw_broom-mike-koenig.mp3' %}"), ('Women', "{% static 'palak/felling_-_sumit_ring.mp3' %}")], default='', max_length=50),
        ),
    ]
