# Generated by Django 3.0.5 on 2020-12-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0022_auto_20201202_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_edit',
            name='music',
            field=models.CharField(choices=[('Men', 'sweeping_straw_broom-mike-koenig.mp3'), ('Women', 'felling_-_sumit_ring.mp3')], default='', max_length=50),
        ),
    ]
