# Generated by Django 3.0.5 on 2020-12-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0023_auto_20201202_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_edit',
            name='music',
            field=models.CharField(choices=[('sweeping_straw_broom-mike-koenig.mp3', 'sweeping_straw_broom-mike-koenig.mp3'), ('felling_-_sumit_ring.mp3', 'felling_-_sumit_ring.mp3')], default='', max_length=50),
        ),
    ]
