# Generated by Django 3.0.5 on 2020-12-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0024_auto_20201202_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_edit',
            name='music',
            field=models.CharField(choices=[('MNF Men Voice 1', 'MNF Men Voice 1'), ('MNF Women Voice 1', 'MNF Women Voice 1'), ('MNF child Voice 1', 'MNF child Voice 1'), ('MNF Adult Voice 1', 'MNF Adult Voice 1')], default='', max_length=50),
        ),
    ]
