# Generated by Django 3.0.5 on 2020-12-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('palak', '0026_mnfuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MNFUser',
        ),
    ]
