# Generated by Django 3.0.5 on 2020-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palak', '0027_delete_mnfuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actors', models.FloatField(blank=True, default=0.0, null=True)),
                ('Other_Actors', models.FloatField(blank=True, default=0.0, null=True)),
                ('Production', models.FloatField(blank=True, default=0.0, null=True)),
                ('Director', models.FloatField(blank=True, default=0.0, null=True)),
                ('Producer', models.FloatField(blank=True, default=0.0, null=True)),
                ('post_production', models.FloatField(blank=True, default=0.0, null=True)),
                ('Legal', models.FloatField(blank=True, default=0.0, null=True)),
                ('Marketing', models.FloatField(blank=True, default=0.0, null=True)),
                ('Miscellaneous', models.FloatField(blank=True, default=0.0, null=True)),
                ('Total_Budget', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
